#+TITLE: Dpp

    Qual impacto que causo nos outros?

R: Eu sou uma pessoa que reflete muito sobre as situações e tenta entender os motivos, então sinto que influencio as pessoas ao meu redor a pensar sobre determinadas situações mais a fundo, tentando entender os motivos do outro, ao invés de apenas observar o que foi feito.

    Por que me descontrolo?

R: Não é comum eu me descontrolar, mas quando acontece é porque paro de "pensar racionalmente" nas situações e sou levado pelas minhas emoções momentâneas.

    Quando me motivo?

R: Me motivo quando percebo que existirá uma recompensa no final caso eu me esforce e alcance um objetivo. Quando lembro que após todo o esforço que estou fazendo existirá uma recompensa, me motivo a me esforçar ainda mais para alcançar o que almejo.

    Como ser empático?

R: Na minha visão, ser empático é tentar ao máximo entender os motivos do outro e o que o levou a estar em determinada situação. É não julgar o outro, mesmo não concordando com suas atitudes.

    Isso é possível?

R: Sim, é possível, porém não é tão fácil. É preciso ter uma visão ampla sobre uma determinada situação, para analisar não só a consequência de uma atitude, e sim o contexto como um todo.







1- Qual o impacto que causo nos outros?

2-Por que me descontrolo?

3-Quando me motivo?

4-Como ser empático?

5-Isso é possível?
